import { McpServer, ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { commitTaskDecomposition, decomposeTaskWithAi } from "./ai-tasks";
import { auditMcp, consumeDeleteConfirmation, createDeleteConfirmation, McpPrincipal, requireWrite } from "./mcp-auth";
import { createProject, createTag, createTask, deleteResource, getDeleteImpact, getState, getTask, GtdError, listProjects, listTags, listTasks, reorderTasks, updateProject, updateTag, updateTask } from "./gtd";

const statusSchema=z.enum(["inbox","next","waiting","scheduled","someday","done"]);
const taskPatchSchema=z.object({projectId:z.string().optional().nullable(),parentTaskId:z.string().optional().nullable(),title:z.string().min(1).max(240).optional(),notes:z.string().max(10000).optional(),status:statusSchema.optional(),context:z.string().max(80).optional(),important:z.boolean().optional(),startDate:z.string().optional().nullable(),dueDate:z.string().optional().nullable(),estimate:z.number().int().min(1).max(365).optional(),sortOrder:z.number().int().optional(),tagIds:z.array(z.string()).optional(),dependencyIds:z.array(z.string()).optional()});
const result=(value:unknown,summary:string)=>({content:[{type:"text" as const,text:summary}],structuredContent:value as Record<string,unknown>});
const failure=(error:unknown)=>({content:[{type:"text" as const,text:error instanceof Error?error.message:"操作失败"}],structuredContent:error instanceof GtdError?{error:error.message,status:error.status,details:error.details}:undefined,isError:true});

async function execute(principal:McpPrincipal,name:string,write:boolean,target:{type?:string;id?:string},run:()=>Promise<any>,summary:(value:any)=>string){
  try{if(write)requireWrite(principal);const value=await run();await auditMcp(principal,name,true,target.type,target.id);return result(value,summary(value));}
  catch(error){await auditMcp(principal,name,false,target.type,target.id).catch(()=>undefined);return failure(error);}
}

export function buildMcpServer(principal:McpPrincipal){
  const server=new McpServer({name:"gtd-flow",version:"1.0.0"},{instructions:"先读取 GTD 概览或任务，再使用记录中的 revision 更新。所有删除必须先调用对应 preview_delete 工具，并在 5 分钟内携带确认令牌删除。系统设置不通过 MCP 暴露。"});

  server.registerTool("get_gtd_overview",{title:"获取 GTD 概览",description:"读取收集箱、今天、下一步、等待中、日程、将来/也许、逾期与已完成数量。",inputSchema:z.object({})},()=>execute(principal,"get_gtd_overview",false,{},async()=>overview(principal.userId),()=>"已读取 GTD 概览"));
  server.registerTool("list_tasks",{title:"查询任务",description:"按 GTD 视图、项目、状态、标签、情境、日期或关键词查询任务，最多返回 100 条。",inputSchema:z.object({query:z.string().optional(),view:z.enum(["inbox","today","important","next","waiting","scheduled","someday","completed"]).optional(),projectId:z.string().optional(),status:statusSchema.optional(),tagId:z.string().optional(),context:z.string().optional(),important:z.boolean().optional(),parentTaskId:z.string().optional(),dueFrom:z.string().optional(),dueTo:z.string().optional(),cursor:z.string().optional(),limit:z.number().int().min(1).max(100).optional()})},(args)=>execute(principal,"list_tasks",false,{},()=>listTasks(principal.userId,args),v=>`找到 ${v.items.length} 个任务`));
  server.registerTool("get_task",{title:"获取任务详情",description:"读取单个任务及其标签、依赖、revision。",inputSchema:z.object({taskId:z.string()})},({taskId})=>execute(principal,"get_task",false,{type:"task",id:taskId},async()=>{const item=await getTask(principal.userId,taskId);if(!item)throw new GtdError("任务不存在",404);return item;},v=>`已读取任务“${v.title}”`));
  server.registerTool("create_task",{title:"创建任务",description:"创建任务或子任务，可同时指定项目、标签、日期与依赖。",inputSchema:taskPatchSchema.extend({title:z.string().min(1).max(240)})},(args)=>execute(principal,"create_task",true,{type:"task"},()=>createTask(principal.userId,{...args,projectId:args.projectId||undefined,parentTaskId:args.parentTaskId||undefined,startDate:args.startDate||undefined,dueDate:args.dueDate||undefined}),v=>`已创建任务“${v.record.title}”`));
  server.registerTool("update_task",{title:"更新任务",description:"使用 expectedRevision 更新任务字段、排期、项目、父子关系、标签或依赖。",inputSchema:z.object({taskId:z.string(),expectedRevision:z.number().int().min(1),patch:taskPatchSchema})},({taskId,expectedRevision,patch})=>execute(principal,"update_task",true,{type:"task",id:taskId},()=>updateTask(principal.userId,taskId,expectedRevision,{...patch,projectId:patch.projectId||undefined,parentTaskId:patch.parentTaskId||undefined,startDate:patch.startDate||undefined,dueDate:patch.dueDate||undefined}),v=>`已更新任务“${v.record.title}”`));
  server.registerTool("complete_task",{title:"完成或恢复任务",description:"将任务标记为已完成，或恢复到下一步。",inputSchema:z.object({taskId:z.string(),expectedRevision:z.number().int().min(1),completed:z.boolean().default(true)})},({taskId,expectedRevision,completed})=>execute(principal,"complete_task",true,{type:"task",id:taskId},()=>updateTask(principal.userId,taskId,expectedRevision,{status:completed?"done":"next"}),v=>completed?`已完成“${v.record.title}”`:`已恢复“${v.record.title}”`));
  server.registerTool("reorder_tasks",{title:"重新排序任务",description:"按给定任务 ID 顺序更新排序，需要最新 dataVersion。",inputSchema:z.object({orderedTaskIds:z.array(z.string()).min(1).max(1000),expectedDataVersion:z.number().int().min(0)})},({orderedTaskIds,expectedDataVersion})=>execute(principal,"reorder_tasks",true,{type:"task"},()=>reorderTasks(principal.userId,orderedTaskIds,expectedDataVersion),()=>"任务顺序已更新"));
  server.registerTool("set_task_dependencies",{title:"设置任务依赖",description:"替换任务的完成到开始依赖，拒绝跨账号引用与循环依赖。",inputSchema:z.object({taskId:z.string(),expectedRevision:z.number().int().min(1),dependencyIds:z.array(z.string()).max(100)})},({taskId,expectedRevision,dependencyIds})=>execute(principal,"set_task_dependencies",true,{type:"task",id:taskId},()=>updateTask(principal.userId,taskId,expectedRevision,{dependencyIds}),v=>`已更新“${v.record.title}”的依赖`));

  registerDeleteTools(server,principal,"task");
  server.registerTool("list_projects",{title:"列出项目",description:"分页读取项目及 revision，单页最多 100 条。",inputSchema:z.object({cursor:z.string().optional(),limit:z.number().int().min(1).max(100).optional()})},(args)=>execute(principal,"list_projects",false,{type:"project"},()=>listProjects(principal.userId,args),v=>`找到 ${v.items.length} 个项目`));
  server.registerTool("create_project",{title:"创建项目",description:"创建 GTD 项目，可设置任务主题颜色。",inputSchema:z.object({name:z.string().min(1).max(80),color:z.string().optional(),backgroundColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional(),textColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional(),borderColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional()})},(args)=>execute(principal,"create_project",true,{type:"project"},()=>createProject(principal.userId,args),v=>`已创建项目“${v.record.name}”`));
  server.registerTool("update_project",{title:"更新项目",description:"更新项目名称或任务主题颜色。",inputSchema:z.object({projectId:z.string(),expectedRevision:z.number().int().min(1),name:z.string().min(1).max(80).optional(),color:z.string().optional(),backgroundColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional(),textColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional(),borderColor:z.string().regex(/^#[0-9a-f]{6}$/i).optional()})},({projectId,expectedRevision,...patch})=>execute(principal,"update_project",true,{type:"project",id:projectId},()=>updateProject(principal.userId,projectId,expectedRevision,patch),v=>`已更新项目“${v.record.name}”`));
  registerDeleteTools(server,principal,"project");

  server.registerTool("list_tags",{title:"列出标签",description:"分页读取任务标签及 revision，单页最多 100 条。",inputSchema:z.object({cursor:z.string().optional(),limit:z.number().int().min(1).max(100).optional()})},(args)=>execute(principal,"list_tags",false,{type:"tag"},()=>listTags(principal.userId,args),v=>`找到 ${v.items.length} 个标签`));
  server.registerTool("create_tag",{title:"创建标签",description:"创建任务标签。",inputSchema:z.object({name:z.string().min(1).max(40)})},(args)=>execute(principal,"create_tag",true,{type:"tag"},()=>createTag(principal.userId,args),v=>`已创建标签“${v.record.name}”`));
  server.registerTool("update_tag",{title:"更新标签",description:"更新标签名称。",inputSchema:z.object({tagId:z.string(),expectedRevision:z.number().int().min(1),name:z.string().min(1).max(40)})},({tagId,expectedRevision,name})=>execute(principal,"update_tag",true,{type:"tag",id:tagId},()=>updateTag(principal.userId,tagId,expectedRevision,{name}),v=>`已更新标签“${v.record.name}”`));
  registerDeleteTools(server,principal,"tag");

  server.registerTool("decompose_task_with_ai",{title:"AI 拆分任务",description:"使用 Web 中已保存的 AI 配置生成可编辑子任务草稿，不写入数据库。",inputSchema:z.object({taskId:z.string(),instruction:z.string().max(2000).optional()})},({taskId,instruction})=>execute(principal,"decompose_task_with_ai",true,{type:"task",id:taskId},async()=>{const task=await getTask(principal.userId,taskId);if(!task)throw new GtdError("任务不存在",404);return decomposeTaskWithAi(principal.userId,{title:task.title,notes:task.notes,dueDate:task.dueDate,instruction});},v=>`已生成 ${v.items.length} 个拆分步骤草稿`));
  const itemSchema=z.object({tempId:z.string(),title:z.string().min(1).max(240),notes:z.string().optional().default(""),estimate:z.number().int().min(1).max(90).default(1),startDate:z.string().optional(),dueDate:z.string().optional(),dependsOn:z.array(z.string()).default([])});
  server.registerTool("commit_task_decomposition",{title:"提交 AI 拆分草稿",description:"校验编辑后的草稿并原子创建子任务及依赖。",inputSchema:z.object({parentTaskId:z.string(),items:z.array(itemSchema).min(1).max(12)})},({parentTaskId,items})=>execute(principal,"commit_task_decomposition",true,{type:"task",id:parentTaskId},()=>commitTaskDecomposition(principal.userId,parentTaskId,items),v=>`已创建 ${v.tasks.length} 个子任务`));

  server.registerResource("gtd-overview","gtd://overview",{title:"GTD 概览",description:"当前账号的 GTD 智能视图统计",mimeType:"application/json"},async(uri)=>({contents:[{uri:uri.href,mimeType:"application/json",text:JSON.stringify(await overview(principal.userId))}]}));
  server.registerResource("gtd-views",new ResourceTemplate("gtd://views/{view}",{list:undefined}),{title:"GTD 智能视图",description:"收集箱、今天、下一步、等待中、日程、将来/也许与已完成任务",mimeType:"application/json"},async(uri,variables)=>({contents:[{uri:uri.href,mimeType:"application/json",text:JSON.stringify(await listTasks(principal.userId,{view:String(variables.view),limit:100}))}]}));
  server.registerResource("gtd-task",new ResourceTemplate("gtd://tasks/{id}",{list:undefined}),{title:"任务详情",mimeType:"application/json"},async(uri,variables)=>({contents:[{uri:uri.href,mimeType:"application/json",text:JSON.stringify(await getTask(principal.userId,String(variables.id)))}]}));
  server.registerResource("gtd-project",new ResourceTemplate("gtd://projects/{id}",{list:undefined}),{title:"项目详情",mimeType:"application/json"},async(uri,variables)=>{const s=await getState(principal.userId);return{contents:[{uri:uri.href,mimeType:"application/json",text:JSON.stringify({project:s.projects.find((x)=>x.id===String(variables.id))||null,tasks:(await listTasks(principal.userId,{projectId:String(variables.id),limit:100})).items})}]};});

  server.registerPrompt("weekly_review",{title:"每周回顾",description:"根据当前 GTD 数据生成每周回顾流程",argsSchema:{}},async()=>{const data=await overview(principal.userId);return{description:"GTD Flow 每周回顾",messages:[{role:"user",content:{type:"text",text:`请根据以下 GTD 概览带我完成每周回顾：\n${JSON.stringify(data,null,2)}\n依次清空收集箱、检查项目与等待中任务、处理逾期事项，并确定下周重点。`}}]};});
  server.registerPrompt("plan_my_day",{title:"规划今天",description:"根据今天、逾期、重要与依赖状态规划当日行动",argsSchema:{}},async()=>{const data=await listTasks(principal.userId,{limit:100});return{description:"GTD Flow 今日计划",messages:[{role:"user",content:{type:"text",text:`请根据以下任务规划今天，优先考虑逾期、重要、今天到期和依赖已满足的任务：\n${JSON.stringify(data.items,null,2)}`}}]};});
  return server;
}

function registerDeleteTools(server:McpServer,principal:McpPrincipal,type:"task"|"project"|"tag"){
  const idKey=type==="task"?"taskId":type==="project"?"projectId":"tagId";const title=type==="task"?"任务":type==="project"?"项目":"标签";
  server.registerTool(`preview_delete_${type}`,{title:`预览删除${title}`,description:`返回删除${title}的影响范围和 5 分钟一次性确认令牌。`,inputSchema:z.object({[idKey]:z.string()}) as any,annotations:{destructiveHint:false,readOnlyHint:false}},(args:any)=>execute(principal,`preview_delete_${type}`,true,{type,id:args[idKey]},async()=>{const preview=await getDeleteImpact(principal.userId,type,args[idKey]);const confirmation=await createDeleteConfirmation(principal,type,args[idKey],preview.revision);return{...preview,...confirmation};},()=>`已生成删除${title}预览，请核对影响范围`));
  server.registerTool(`delete_${type}`,{title:`删除${title}`,description:`使用 preview_delete_${type} 返回的一次性令牌执行删除。`,inputSchema:z.object({[idKey]:z.string(),confirmationToken:z.string()}) as any,annotations:{destructiveHint:true,idempotentHint:false}},(args:any)=>execute(principal,`delete_${type}`,true,{type,id:args[idKey]},async()=>{const revision=await consumeDeleteConfirmation(principal,type,args[idKey],args.confirmationToken);return deleteResource(principal.userId,type,args[idKey],revision);},()=>`${title}已删除`));
}

async function overview(userId:string){const state=await getState(userId),now=new Date().toISOString().slice(0,10),open=state.tasks.filter((x)=>x.status!=="done");return{dataVersion:state.dataVersion,totalOpen:open.length,inbox:open.filter((x)=>x.status==="inbox").length,today:open.filter((x)=>x.startDate===now||x.dueDate===now).length,important:open.filter((x)=>x.important).length,next:open.filter((x)=>x.status==="next").length,waiting:open.filter((x)=>x.status==="waiting").length,scheduled:open.filter((x)=>x.status==="scheduled").length,someday:open.filter((x)=>x.status==="someday").length,overdue:open.filter((x)=>x.dueDate&&x.dueDate<now).length,completed:state.tasks.length-open.length,projects:state.projects.length,tags:state.tags.length};}
