CREATE TABLE IF NOT EXISTS smtp_configs (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  host TEXT NOT NULL,
  port INTEGER NOT NULL CHECK (port BETWEEN 1 AND 65535),
  username TEXT NOT NULL DEFAULT '',
  encrypted_password TEXT NOT NULL,
  mail_from TEXT NOT NULL,
  secure BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
