import pg from "pg";
import { sendNotification, type NotificationPayload } from "../app/api/_lib/notification-delivery";
import type { NotificationChannel } from "../app/api/_lib/notifications";

const {Pool}=pg,pool=new Pool({connectionString:process.env.DATABASE_URL,max:Number(process.env.DB_POOL_SIZE||4)}),retryMinutes=[0,1,4,10];
type Delivery={id:string;reminder_id:string;channel:NotificationChannel;attempts:number;user_id:string;task_id:string;title:string;notes:string;due_date?:string;project_id?:string};

async function claim():Promise<Delivery|undefined>{const client=await pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE task_reminders SET status='missed',updated_at=NOW() WHERE status IN ('pending','processing') AND remind_at < NOW()-INTERVAL '15 minutes'`);await client.query(`UPDATE reminder_deliveries d SET status='skipped',last_error='提醒时间已错过超过 15 分钟',updated_at=NOW() FROM task_reminders r WHERE d.reminder_id=r.id AND r.status='missed' AND d.status NOT IN ('sent','skipped')`);const result=await client.query<Delivery>(`WITH candidate AS (SELECT d.id FROM reminder_deliveries d JOIN task_reminders r ON r.id=d.reminder_id WHERE r.status IN ('pending','processing') AND r.remind_at>=NOW()-INTERVAL '15 minutes' AND ((d.status IN ('pending','failed') AND d.next_attempt_at<=NOW()) OR (d.status='processing' AND d.locked_at<NOW()-INTERVAL '2 minutes')) ORDER BY d.next_attempt_at FOR UPDATE OF d SKIP LOCKED LIMIT 1) UPDATE reminder_deliveries d SET status='processing',locked_at=NOW(),updated_at=NOW() FROM candidate c,task_reminders r,tasks t WHERE d.id=c.id AND r.id=d.reminder_id AND t.id=r.task_id RETURNING d.id,d.reminder_id,d.channel,d.attempts,r.user_id,r.task_id,t.title,t.notes,t.due_date,t.project_id`);await client.query("COMMIT");return result.rows[0];}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}

async function finish(item:Delivery,error?:unknown){const attempts=item.attempts+1,lastError=error instanceof Error?error.message:String(error||"");const client=await pool.connect();try{await client.query("BEGIN");if(!error)await client.query("UPDATE reminder_deliveries SET status='sent',attempts=$1,sent_at=NOW(),locked_at=NULL,last_error=NULL,updated_at=NOW() WHERE id=$2",[attempts,item.id]);else if(attempts<4)await client.query("UPDATE reminder_deliveries SET status='failed',attempts=$1,next_attempt_at=NOW()+($2||' minutes')::interval,locked_at=NULL,last_error=$3,updated_at=NOW() WHERE id=$4",[attempts,String(retryMinutes[attempts]),lastError.slice(0,1000),item.id]);else await client.query("UPDATE reminder_deliveries SET status='failed',attempts=$1,locked_at=NULL,last_error=$2,updated_at=NOW() WHERE id=$3",[attempts,lastError.slice(0,1000),item.id]);await client.query(`UPDATE task_reminders r SET status=CASE WHEN EXISTS(SELECT 1 FROM reminder_deliveries d WHERE d.reminder_id=r.id AND d.status IN ('pending','processing')) THEN 'processing' WHEN EXISTS(SELECT 1 FROM reminder_deliveries d WHERE d.reminder_id=r.id AND d.status='failed' AND d.attempts<4) THEN 'processing' WHEN NOT EXISTS(SELECT 1 FROM reminder_deliveries d WHERE d.reminder_id=r.id AND d.status<>'sent') THEN 'sent' WHEN EXISTS(SELECT 1 FROM reminder_deliveries d WHERE d.reminder_id=r.id AND d.status='sent') THEN 'partial' ELSE 'failed' END,updated_at=NOW() WHERE r.id=$1`,[item.reminder_id]);await client.query("COMMIT");}catch(next){await client.query("ROLLBACK");throw next;}finally{client.release();}}

async function tick(){for(let count=0;count<25;count++){const item=await claim();if(!item)break;const payload:NotificationPayload={version:1,event:"task.reminder",deliveryId:item.id,reminderId:item.reminder_id,occurredAt:new Date().toISOString(),task:{id:item.task_id,title:item.title,notes:item.notes,dueDate:item.due_date||undefined,projectId:item.project_id||undefined},url:`https://${process.env.DOMAIN||"localhost"}/?task=${encodeURIComponent(item.task_id)}`};try{await sendNotification(item.user_id,item.channel,payload);await finish(item);}catch(error){console.error(`Reminder delivery ${item.id} failed`,error instanceof Error?error.message:error);await finish(item,error);}}}

console.info("GTD Flow reminder worker started");await tick();setInterval(()=>void tick().catch(error=>console.error("Reminder worker tick failed",error)),15_000);
